# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-21 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginAndRegistration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='travels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('joiners', models.ManyToManyField(related_name='joined_trips', to='loginAndRegistration.User')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='loginAndRegistration.User')),
            ],
        ),
    ]
